### ISSUE TITLE
Removing and reinstalling Reverse Proxy/Mailpile leaves sites in broken state

### ISSUE THREAD

**Issue by Bugsbane** [cznweb/genesis#464]
When I removed Reverse Proxy and Mailpile plugins and reinstalled them, it seems to have left "My Websites" in an unusual state.
1. Mailpile plugin seemed to install fine the first (and second) time, but on the third and fourth time I get this error during the "Loading Mailpile" phase of installation:
   `"requires application "Mailpile" (package: mailpile, executable: mp)"`This is despite having just asked it to install Mailpile, and Mailpile being listed in App Store > Installed (albeit with an error icon next to it). It doesn't show in "My Applications"
2. Going into My Applications > Reverse Proxy shows a website setup called Mailpile. When I try to delete it, I get the error: `Website removal failed: [Errno 2] No such file or directory: '/var/lib/mailpile'`. After this error, the website still doesn't disappear though.
3. After removing both Mailpile and Reverse Proxy plugins, the website "mailpile" continues to show in "My Websites" as type "unknown". It shows as type "Reverse Proxy" until Reverse Proxy plugin is uninstalled. Trying to remove it from "My Websites" gives the error: `"Website removal failed: 'NoneType' object has no attribute 'pre_remove'"` Trying to configure the site with a new name and port number (81) got a nice crash out of Genesis. Here's the backtrace:
   ## Genesis 0.6.0 bug report
   
   System: Linux hal 3.12.27-1-MANJARO #1 SMP PREEMPT Sat Aug 30 08:34:41 UTC 2014 x86_64 GNU/Linux
   
   Detected platform: arch
   Detected distro: Manjaro Linux
   
   Python: 2.7.8
   
   Config path: /etc/genesis/users/MYUSERNAME.conf
   
   Traceback (most recent call last):
     File "/usr/lib/python2.7/site-packages/genesis/core/application.py", line 166, in dispatcher
       self.start_response)
     File "/usr/lib/python2.7/site-packages/genesis/api/urlhandler.py", line 89, in url_handler
       return handler(req, start_response)
     File "/usr/lib/python2.7/site-packages/genesis/plugins/core/root.py", line 282, in handle_generic
       result = handler.event(event, params, vars = vars)
     File "/usr/lib/python2.7/site-packages/genesis/api/helpers.py", line 115, in event
       return handler(event, _params, *_kwparams)
     File "/usr/lib/python2.7/site-packages/genesis/plugins/webapps/main.py", line 286, in on_submit
       self.mgr.nginx_edit(self._edit, w)
     File "/usr/lib/python2.7/site-packages/genesis/plugins/webapps/backend.py", line 321, in nginx_edit
       os.path.join('/srv/http/webapps', site.name))
     File "/usr/lib/python2.7/shutil.py", line 302, in move
       copy2(src, real_dst)
     File "/usr/lib/python2.7/shutil.py", line 130, in copy2
       copyfile(src, dst)
     File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
       with open(src, 'rb') as fsrc:
   IOError: [Errno 2] No such file or directory: '/srv/http/webapps/mailpile'
   
   Loaded plugins:
   db-mariadb
   db-sqlite3
   nodejs
   owncloud
   php
   syncthing
   wordpress
   
   Log:
   (Showing only the last 50 entries)
   
   2014-09-19 16:43:29,207 [DEBUG] application: Calling handler for /core/progress
   2014-09-19 16:43:29,230 [DEBUG] application: Finishing /core/progress
   2014-09-19 16:43:31,208 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:31,218 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:31,222 [DEBUG] application: Calling handler for /core/progress
   2014-09-19 16:43:31,255 [DEBUG] application: Finishing /core/progress
   2014-09-19 16:43:31,261 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:31,267 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:31,272 [DEBUG] application: Calling handler for /core/progress
   2014-09-19 16:43:31,300 [DEBUG] application: Finishing /core/progress
   2014-09-19 16:43:33,280 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:33,287 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:33,291 [DEBUG] application: Calling handler for /core/progress
   2014-09-19 16:43:33,314 [DEBUG] application: Finishing /core/progress
   2014-09-19 16:43:33,318 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:33,324 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:33,328 [DEBUG] application: Calling handler for /core/progress
   2014-09-19 16:43:33,356 [DEBUG] application: Finishing /core/progress
   2014-09-19 16:43:33,416 [DEBUG] application: Dispatching /handle/button/click/config/0
   2014-09-19 16:43:33,425 [DEBUG] application: Dispatching /handle/button/click/config/0
   2014-09-19 16:43:33,429 [DEBUG] application: Calling handler for /handle/button/click/config/0
   2014-09-19 16:43:33,610 [DEBUG] application: Finishing /handle/button/click/config/0
   2014-09-19 16:43:35,368 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:35,379 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:35,383 [DEBUG] application: Calling handler for /core/progress
   2014-09-19 16:43:35,416 [DEBUG] application: Finishing /core/progress
   2014-09-19 16:43:35,422 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:35,430 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:35,432 [DEBUG] application: Calling handler for /core/progress
   2014-09-19 16:43:35,456 [DEBUG] application: Finishing /core/progress
   2014-09-19 16:43:37,427 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:37,441 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:37,445 [DEBUG] application: Calling handler for /core/progress
   2014-09-19 16:43:37,479 [DEBUG] application: Finishing /core/progress
   2014-09-19 16:43:37,487 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:37,498 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:37,502 [DEBUG] application: Calling handler for /core/progress
   2014-09-19 16:43:37,539 [DEBUG] application: Finishing /core/progress
   2014-09-19 16:43:39,488 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:39,495 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:39,500 [DEBUG] application: Calling handler for /core/progress
   2014-09-19 16:43:39,525 [DEBUG] application: Finishing /core/progress
   2014-09-19 16:43:39,572 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:39,581 [DEBUG] application: Dispatching /core/progress
   2014-09-19 16:43:39,586 [DEBUG] application: Calling handler for /core/progress
   2014-09-19 16:43:39,614 [DEBUG] application: Finishing /core/progress
   2014-09-19 16:43:40,096 [DEBUG] application: Dispatching /handle/dialog/submit/dlgEdit
   2014-09-19 16:43:40,108 [DEBUG] application: Dispatching /handle/dialog/submit/dlgEdit
   2014-09-19 16:43:40,110 [DEBUG] application: Calling handler for /handle/dialog/submit/dlgEdit

**Comment by Bugsbane** [comment]
I'm still having issues with this. Mailpile is no longer showing in my installed plugins or websites, but when I try to install it, I still get the error message in point 1 about mailpile not being installed. I tried pacman -S mailpile and pacman -S mp but it says it's an unknown target.

Given that I installed Genesis on Manjaro, instead of using arkOS proper, I'm wondering if I'm missing an arkOS repository with mailpile packages or something, thus it doesn't get installed.
