### ISSUE TITLE
Running 'Setup' in mailserver crashes Genesis

### ISSUE THREAD

**Issue by shayandoust** [cznweb/genesis#502]
Genesis 0.6.0 bug report
--------------------

System: Linux arkos 3.12.24-1-ARCH #1 PREEMPT Thu Jul 10 23:57:15 MDT 2014 armv6l GNU/Linux

Detected platform: arkos
Detected distro: Linux 3.12.24-1-ARCH armv6l

Python: 2.7.8

Config path: /etc/genesis/users/shayan_doust.conf

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/genesis/core/application.py", line 166, in dispatcher
    self.start_response)
  File "/usr/lib/python2.7/site-packages/genesis/api/urlhandler.py", line 89, in url_handler
    return handler(req, start_response)
  File "/usr/lib/python2.7/site-packages/genesis/plugins/core/root.py", line 282, in handle_generic
    result = handler.event(event, params, vars = vars)
  File "/usr/lib/python2.7/site-packages/genesis/api/helpers.py", line 115, in event
    return handler(event, *params, **kwparams)
  File "/var/lib/genesis/plugins/email/main.py", line 174, in on_click
    self._mc.initial_setup()
  File "/var/lib/genesis/plugins/email/backend.py", line 279, in initial_setup
    if 'vmail' in [x['name'] for x in dbase.get_dbs()]:
  File "/var/lib/genesis/plugins/db-sqlite3/main.py", line 57, in get_dbs
    self.chkpath()
  File "/var/lib/genesis/plugins/db-sqlite3/main.py", line 71, in chkpath
    gid = int(users.get_group("sqlite3", users.get_all_groups()).gid)
  File "/usr/lib/python2.7/site-packages/genesis/plugins/users/backend.py", line 95, in get_group
    return filter(lambda x:x.name == name, groups)[0]
IndexError: list index out of range

Loaded plugins:
basicsite
db-sqlite3
email

Log:
(Showing only the last 50 entries)

2015-03-13 12:30:40,498 [DEBUG] application: Calling handler for /handle/category/click/syncthingplugin
2015-03-13 12:30:40,946 [DEBUG] application: Finishing /handle/category/click/syncthingplugin
2015-03-13 12:30:42,348 [DEBUG] application: Dispatching /core/progress
2015-03-13 12:30:42,450 [DEBUG] application: Dispatching /core/progress
2015-03-13 12:30:42,500 [DEBUG] application: Calling handler for /core/progress
2015-03-13 12:30:42,601 [DEBUG] application: Finishing /core/progress
2015-03-13 12:30:44,692 [DEBUG] application: Dispatching /core/progress
2015-03-13 12:30:44,807 [DEBUG] application: Dispatching /core/progress
2015-03-13 12:30:44,840 [DEBUG] application: Calling handler for /core/progress
2015-03-13 12:30:44,940 [DEBUG] application: Finishing /core/progress
2015-03-13 12:30:45,635 [DEBUG] application: Dispatching /handle/servicecontrol/click/services
2015-03-13 12:30:45,739 [DEBUG] application: Dispatching /handle/servicecontrol/click/services
2015-03-13 12:30:45,767 [DEBUG] application: Calling handler for /handle/servicecontrol/click/services
2015-03-13 12:30:46,246 [DEBUG] application: Finishing /handle/servicecontrol/click/services
2015-03-13 12:30:47,026 [DEBUG] application: Dispatching /core/progress
2015-03-13 12:30:47,128 [DEBUG] application: Dispatching /core/progress
2015-03-13 12:30:47,167 [DEBUG] application: Calling handler for /core/progress
2015-03-13 12:30:47,268 [DEBUG] application: Finishing /core/progress
2015-03-13 12:30:49,116 [DEBUG] application: Dispatching /handle/servicecontrol/click/start/syncthing@syncthing/system
2015-03-13 12:30:49,220 [DEBUG] application: Dispatching /handle/servicecontrol/click/start/syncthing@syncthing/system
2015-03-13 12:30:49,247 [DEBUG] application: Calling handler for /handle/servicecontrol/click/start/syncthing@syncthing/system
2015-03-13 12:30:50,006 [DEBUG] application: Finishing /handle/servicecontrol/click/start/syncthing@syncthing/system
2015-03-13 12:30:50,034 [DEBUG] application: Dispatching /core/progress
2015-03-13 12:30:50,198 [DEBUG] application: Dispatching /core/progress
2015-03-13 12:30:50,287 [DEBUG] application: Calling handler for /core/progress
2015-03-13 12:30:50,502 [DEBUG] application: Finishing /core/progress
2015-03-13 12:30:52,762 [DEBUG] application: Dispatching /core/progress
2015-03-13 12:30:53,001 [DEBUG] application: Dispatching /core/progress
2015-03-13 12:30:53,088 [DEBUG] application: Calling handler for /core/progress
2015-03-13 12:30:53,297 [DEBUG] application: Finishing /core/progress
2015-03-13 12:30:54,478 [DEBUG] application: Dispatching /handle/category/click/configplugin
2015-03-13 12:30:54,697 [DEBUG] application: Dispatching /handle/category/click/configplugin
2015-03-13 12:30:54,758 [DEBUG] application: Calling handler for /handle/category/click/configplugin
2015-03-13 12:30:55,835 [DEBUG] application: Finishing /handle/category/click/configplugin
2015-03-13 12:30:55,872 [DEBUG] application: Dispatching /core/progress
2015-03-13 12:30:56,085 [DEBUG] application: Dispatching /core/progress
2015-03-13 12:30:56,181 [DEBUG] application: Calling handler for /core/progress
2015-03-13 12:30:56,383 [DEBUG] application: Finishing /core/progress
2015-03-13 12:30:56,989 [DEBUG] application: Dispatching /handle/button/click/updaction
2015-03-13 12:30:57,194 [DEBUG] application: Dispatching /handle/button/click/updaction
2015-03-13 12:30:57,280 [DEBUG] application: Calling handler for /handle/button/click/updaction
2015-03-13 12:30:58,291 [DEBUG] application: Finishing /handle/button/click/updaction
2015-03-13 12:30:58,451 [DEBUG] application: Dispatching /core/progress
2015-03-13 12:30:58,648 [DEBUG] application: Dispatching /core/progress
2015-03-13 12:30:58,751 [DEBUG] application: Calling handler for /core/progress
2015-03-13 12:30:58,960 [DEBUG] application: Finishing /core/progress
2015-03-13 12:30:59,957 [DEBUG] application: Dispatching /handle/dialog/submit/dlgUpdate
2015-03-13 12:31:00,177 [DEBUG] application: Dispatching /handle/dialog/submit/dlgUpdate
2015-03-13 12:31:00,259 [DEBUG] application: Calling handler for /handle/dialog/submit/dlgUpdate

**Comment by peakwinter** [comment]
You need to manually update Genesis via the Packages pane, or with `sudo pacman -Sy genesis` from the command line.
