### ISSUE TITLE
Upgrading packages via Genesis gives this error

### ISSUE THREAD

**Issue by Bugsbane** [cznweb/genesis#506]
...at least, I think this error came up while I was testing the package upgrade process:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/kraken/kraken/auth.py", line 88, in decorator
    return func(*args, **kwargs)
  File "/home/vagrant/kraken/kraken/frameworks/config.py", line 24, in arkos_config
    return jsonify(config=config.config, hostname=sysconfig.get_hostname(),
  File "/home/vagrant/core/arkos/system/sysconfig.py", line 15, in get_hostname
    with open('/etc/hostname', 'r') as f:
IOError: [Errno 2] No such file or directory: '/etc/hostname'

**Comment by peakwinter** [comment]
Hmm, that's an odd one. Maybe the Vagrant image doesn't have a default hostname file? Try `echo "vagrant" > /etc/hostname`

**Comment by Bugsbane** [comment]
Now when I try to upgrade, it asks me to wait, then after a few seconds gives a notification with nothing but a list of packages. A second or two later I get this error (and no errors in the terminal):

Failed to install: error: failed to commit transaction (conflicting files)

**Comment by peakwinter** [comment]
Yup, pacman encountered a conflict so it couldn't install a package. Genesis will have to catch those and produce a bit better error message in those instances. For now you can check the problem with `pacman -Syu` from the command line.

**Comment by Bugsbane** [comment]
Looks like this is the error:

> arkos-openldap: /etc/openldap/ldap.conf exists in filesystem

**Comment by peakwinter** [comment]
Ok then that is by extension my problem XD Will look into it!

**Comment by peakwinter** [comment]
An update to the `arkos-openldap` package has been pushed that should resolve the conflict. You can try a full update again after pressing the Refresh button.
