### ISSUE TITLE
Error generated on choosing the Security / Preferences menu options

### ISSUE THREAD

**Issue by Bugsbane** [cznweb/genesis#507]
I get this any time I go to the Settings > Security menu item in Genesis 0.7. I get something similar if I click Settings > Preferences:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/home/vagrant/kraken/kraken/auth.py", line 88, in decorator
    return func(*args, **kwargs)
  File "/home/vagrant/kraken/kraken/frameworks/security.py", line 39, in get
    return jsonify(jails=security.get_defense_rules())
  File "/home/vagrant/core/arkos/security.py", line 209, in get_defense_rules
    cfg = get_jail_config()
  File "/home/vagrant/core/arkos/security.py", line 141, in get_jail_config
    raise Exception("Fail2Ban config not found or not readable")
Exception: Fail2Ban config not found or not readable

**Comment by peakwinter** [comment]
Yup, Fail2ban isn't installed by default in the Vagrant image (probably). Not that it would do anything anyway, that part has yet to be plugged in in Genesis. Will look at it though, thanks!

**Comment by peakwinter** [comment]
Fixed in latest box config (pushing a new one shortly).
