### ISSUE TITLE
update doesn't work

### ISSUE THREAD

**Issue by skuydi** [cznweb/genesis#519]
When  I do the update I got this error

Sorry, an error has occurred.
Genesis encountered an error when trying to perform your last requested operation, and it cannot continue it.
You can try again...
...by refreshing the page. In some cases, resetting the session may also help

THE FULL LOG

Genesis 0.6.0 bug report
--------------------

System: Linux arkos 3.12.24-1-ARCH #1 PREEMPT Thu Jul 10 23:57:15 MDT 2014 armv6l GNU/Linux

Detected platform: arkos
Detected distro: Linux 3.12.24-1-ARCH armv6l

Python: 2.7.8

Config path: /etc/genesis/users/root.conf

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/genesis/core/application.py", line 166, in dispatcher
    self.start_response)
  File "/usr/lib/python2.7/site-packages/genesis/api/urlhandler.py", line 89, in url_handler
    return handler(req, start_response)
  File "/usr/lib/python2.7/site-packages/genesis/plugins/core/root.py", line 282, in handle_generic
    result = handler.event(event, params, vars = vars)
  File "/usr/lib/python2.7/site-packages/genesis/api/helpers.py", line 115, in event
    return handler(event, *params, **kwparams)
  File "/usr/lib/python2.7/site-packages/genesis/plugins/config/main.py", line 115, in on_submit
    shell('pacman -S --noconfirm genesis')
NameError: global name 'shell' is not defined

Loaded plugins:
samba

Log:
(Showing only the last 50 entries)

2015-06-17 14:28:19,463 [DEBUG] application: Calling handler for /handle/category/click/sysconfigplugin
2015-06-17 14:28:24,553 [DEBUG] application: Finishing /handle/category/click/sysconfigplugin
2015-06-17 14:28:24,578 [DEBUG] application: Dispatching /core/progress
2015-06-17 14:28:24,678 [DEBUG] application: Dispatching /core/progress
2015-06-17 14:28:24,720 [DEBUG] application: Calling handler for /core/progress
2015-06-17 14:28:24,820 [DEBUG] application: Finishing /core/progress
2015-06-17 14:28:26,852 [DEBUG] application: Dispatching /core/progress
2015-06-17 14:28:26,947 [DEBUG] application: Dispatching /core/progress
2015-06-17 14:28:26,983 [DEBUG] application: Calling handler for /core/progress
2015-06-17 14:28:27,083 [DEBUG] application: Finishing /core/progress
2015-06-17 14:28:31,235 [DEBUG] application: Dispatching /core/progress
2015-06-17 14:28:31,332 [DEBUG] application: Dispatching /core/progress
2015-06-17 14:28:31,378 [DEBUG] application: Calling handler for /core/progress
2015-06-17 14:28:31,479 [DEBUG] application: Finishing /core/progress
2015-06-17 14:28:31,496 [DEBUG] application: Dispatching /handle/category/click/configplugin
2015-06-17 14:28:31,592 [DEBUG] application: Dispatching /handle/category/click/configplugin
2015-06-17 14:28:31,632 [DEBUG] application: Calling handler for /handle/category/click/configplugin
2015-06-17 14:28:32,120 [DEBUG] application: Finishing /handle/category/click/configplugin
2015-06-17 14:28:33,523 [DEBUG] application: Dispatching /core/progress
2015-06-17 14:28:33,617 [DEBUG] application: Dispatching /core/progress
2015-06-17 14:28:33,643 [DEBUG] application: Calling handler for /core/progress
2015-06-17 14:28:33,744 [DEBUG] application: Finishing /core/progress
2015-06-17 14:28:36,246 [DEBUG] application: Dispatching /core/progress
2015-06-17 14:28:36,344 [DEBUG] application: Dispatching /core/progress
2015-06-17 14:28:36,382 [DEBUG] application: Calling handler for /core/progress
2015-06-17 14:28:36,482 [DEBUG] application: Finishing /core/progress
2015-06-17 14:28:37,232 [DEBUG] application: Dispatching /handle/button/click/updaction
2015-06-17 14:28:37,330 [DEBUG] application: Dispatching /handle/button/click/updaction
2015-06-17 14:28:37,355 [DEBUG] application: Calling handler for /handle/button/click/updaction
2015-06-17 14:28:40,434 [DEBUG] application: Finishing /handle/button/click/updaction
2015-06-17 14:28:40,457 [DEBUG] application: Dispatching /core/progress
2015-06-17 14:28:40,552 [DEBUG] application: Dispatching /core/progress
2015-06-17 14:28:40,588 [DEBUG] application: Calling handler for /core/progress
2015-06-17 14:28:40,688 [DEBUG] application: Finishing /core/progress
2015-06-17 14:28:43,356 [DEBUG] application: Dispatching /core/progress
2015-06-17 14:28:43,453 [DEBUG] application: Dispatching /core/progress
2015-06-17 14:28:43,480 [DEBUG] application: Calling handler for /core/progress
2015-06-17 14:28:43,580 [DEBUG] application: Finishing /core/progress
2015-06-17 14:28:44,113 [DEBUG] application: Dispatching /handle/button/click/updaction
2015-06-17 14:28:44,209 [DEBUG] application: Dispatching /handle/button/click/updaction
2015-06-17 14:28:44,249 [DEBUG] application: Calling handler for /handle/button/click/updaction
2015-06-17 14:28:44,735 [DEBUG] application: Finishing /handle/button/click/updaction
2015-06-17 14:28:45,617 [DEBUG] application: Dispatching /core/progress
2015-06-17 14:28:45,710 [DEBUG] application: Dispatching /core/progress
2015-06-17 14:28:45,731 [DEBUG] application: Calling handler for /core/progress
2015-06-17 14:28:45,832 [DEBUG] application: Finishing /core/progress
2015-06-17 14:28:46,463 [DEBUG] application: Dispatching /handle/dialog/submit/dlgUpdate
2015-06-17 14:28:46,560 [DEBUG] application: Dispatching /handle/dialog/submit/dlgUpdate
2015-06-17 14:28:46,585 [DEBUG] application: Calling handler for /handle/dialog/submit/dlgUpdate

**Comment by peakwinter** [comment]
Please see https://github.com/cznweb/genesis/issues/469#issuecomment-57087901, thanks
